<student> ::= <ime> <prezime> <broj> <email> <grad> | <prezime>
<ime> ::= regex(\w+) | "Fipa" | "Filip"
<prezime> ::= "Stojakovic" | "Stoja"
<broj> ::= broj_telefona
<email> ::= mejl_adresa
<grad> ::= "iz" veliki_grad