<verb> ::= "bites" | "PETS" <dga065/182>
<verb> ::= "up-down" | +065/182-135
<S> ::= <subject> "PETS" <predicate> |	regex(<hello>)
<article> ::= "THE" | "A jej"
<subject> ::= <article> <noun>
<predicate> ::= <verb>	<direct-object>
<direct-object> ::= <article> <noun>
<noun> ::= "MAN" | "dog"


